/* Copyright 2020 Ethan Halsall

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>
*/

import fs from "fs";
import path from "path";
import { Transform } from "stream";

import CueBuilder from "./CueBuilder.js";

export default class CueWriter extends Transform {
  constructor({
    startDate,
    cueRollover,
    prependDate,
    dateEntries,
    name,
    icyHeaders,
    fileName,
  }) {
    super({ objectMode: true });

    const FORMAT_MATCHER = /(?:\.([^.]+))?$/;

    this._startDate = startDate;
    this._cueRollover = cueRollover;
    this._name = name;
    this._fileName = fileName;
    this._dateEntries = dateEntries;
    this._prependDate = prependDate;
    this._name = name;
    this._icyHeaders = icyHeaders;

    this._fileNameNoExt = fileName.replace(FORMAT_MATCHER, "");

    this._cueFileWritable = null;
    this._cueFilePromise = Promise.resolve();
    this._cueBuilder = null;
    this._cueRolloverCount = 0;

    this._fileNames = [];
    this._newFile();
  }

  get fileNames() {
    return this._fileNames;
  }

  get cueFilePromise() {
    return this._cueFilePromise;
  }

  set cueRolloverCount(cueRolloverCount) {
    this._cueRolloverCount = cueRolloverCount;
  }

  set startDate(startDate) {
    this._startDate = startDate;
  }

  _newFile() {
    const cueFileName = this._cueRolloverCount
      ? `${this._fileNameNoExt}.${this._cueRolloverCount}.cue`
      : `${this._fileNameNoExt}.cue`;

    this._cueFileWritable = this._openFile(cueFileName);
    this.pipe(this._cueFileWritable);

    this._cueBuilder = new CueBuilder();

    const { name, ...icyHeaders } = this._icyHeaders;

    const cueHeader = CueBuilder.getHeader({
      comment:
        "Generated by IcecastMetadataRecorder https://github.com/eshaz/icecast-metadata-js",
      title: this._name || name || "", // override the header name if passed in and use empty string if undefined
      ...(this._name ? this._icyHeaders : { ...icyHeaders }), // do not duplicate the header name if used in the title
      file: path.basename(this._fileName),
      date: this._startDate.toISOString(),
    });

    this.push(cueHeader, "ascii");
  }

  _openFile(fileName) {
    try {
      fs.mkdirSync(path.dirname(fileName), { recursive: true });
    } catch (e) {
      if (e.code !== "EEXIST") throw e;
    }

    const file = fs.createWriteStream(fileName);

    this._cueFilePromise = new Promise(
      (resolve) => (this._cueResolve = resolve)
    );
    file.on("ready", () => {
      this._fileNames.push(fileName);
    });
    file.on("close", () => {
      this._cueResolve();
    });

    return file;
  }

  async _checkRollover(trackCount, time) {
    if (trackCount + 1 === this._cueRollover) {
      await new Promise((resolve) => {
        this.push(this._cueBuilder.addTrack({ title: "END" }, time), "ascii");
        this._cueRolloverCount++;

        this._cueFileWritable.on("finish", () => {
          this.unpipe(this._cueFileWritable);
          this._newFile();
          resolve();
        });

        this._cueFileWritable.end();
      });
    }
  }

  _transform(meta, encoding, callback) {
    const trackCount = this._cueBuilder.trackCount;

    this._checkRollover(trackCount, meta.time).then(() => {
      /**
       * When there is only one more cue entry remaining
       * until the next rollover, insert an END track.
       * There is no way to indicate the end of a cue file
       * so this will have to do.
       *
       * Reasonable rollover thresholds should be based on your player's limitations.
       * (i.e. Foobar2000 accepts up to 999 tracks in the cue file)
       */
      const timeStamp = new Date(
        this._startDate.getTime() + meta.time * 1000
      ).toISOString();

      const { StreamTitle, ...restOfMetadata } = meta.metadata;

      const track = this._cueBuilder.addTrack(
        {
          title: this._prependDate
            ? `${timeStamp} ${StreamTitle}`
            : StreamTitle,
          ...(this._dateEntries
            ? { date: `${timeStamp.substring(0, 16)}Z` }
            : {}),
          ...restOfMetadata,
        },
        (trackCount || this._cueRolloverCount) && meta.time // force metadata for first track to show immediately
      );

      callback(null, track);
    });
  }
}
