REM Generated by IcecastMetadataRecorder
REM 2020-07-29T21:16:11.222Z
TITLE "Drone Zone"
FILE "music-256k.mp3" WAVE
  TRACK 1 AUDIO
    TITLE "2020-07-29T21:16:11.722Z Djivan Gasparyan - Brother Hunter"
    INDEX 01 00:00:00
  TRACK 2 AUDIO
    TITLE "2020-07-29T21:19:25.722Z Harold Budd & John Foxx - Some Way Through All The Cities"
    INDEX 01 03:14:37