REM Generated by IcecastMetadataRecorder
REM 2020-07-29T21:16:11.222Z
TITLE "Deep Space One"
FILE "music-128k.aac" WAVE
  TRACK 1 AUDIO
    TITLE "2020-07-29T21:16:12.222Z Tlon - In The Shadow Of Unexpectation"
    INDEX 01 00:00:00
  TRACK 2 AUDIO
    TITLE "2020-07-29T21:17:30.222Z SinQ - Rain"
    INDEX 01 01:19:00