REM COMMENT "Generated by IcecastMetadataRecorder https://github.com/eshaz/icecast-metadata-js"
REM BR "128"
REM METAINT "16000"
REM GENRE "Ambient Space"
REM NAME "Deep Space One: Deep ambient electronic and space music. [SomaFM]"
REM NOTICE1 "<BR>This stream requires <a href="http://www.winamp.com/">Winamp</a><BR>"
REM NOTICE2 "SHOUTcast Distributed Network Audio Server/Linux v1.9.5<BR>"
REM PUB "0"
REM URL "http://somafm.com"
REM DATE "2020-07-29T21:16:11.222Z"
TITLE "Deep Space One"
FILE "music-128k.aac" WAVE
  TRACK 1 AUDIO
    REM STREAMURL "http://somafm.com/logos/512/deepspaceone512.png"
    TITLE "Tlon - In The Shadow Of Unexpectation"
    INDEX 01 00:00:00
  TRACK 2 AUDIO
    REM STREAMURL "http://somafm.com/logos/512/deepspaceone512.png"
    TITLE "SinQ - Rain"
    INDEX 01 01:19:00