REM COMMENT "Generated by IcecastMetadataRecorder https://github.com/eshaz/icecast-metadata-js"
REM BR "128"
REM METAINT "16000"
REM DATE "2020-07-29T21:16:11.222Z"
TITLE "Deep Space One"
FILE "music-128k.aac" WAVE
  TRACK 1 AUDIO
    REM STREAMURL "http://somafm.com/logos/512/deepspaceone512.png"
    TITLE "2020-07-29T21:16:12.222Z Tlon - In The Shadow Of Unexpectation"
    INDEX 01 00:00:00
  TRACK 2 AUDIO
    REM STREAMURL "http://somafm.com/logos/512/deepspaceone512.png"
    TITLE "2020-07-29T21:17:30.222Z SinQ - Rain"
    INDEX 01 01:19:00