class CueFileGenerator {
    constructor({name, file}) {
        this._startDate = new Date(Date.now());
        this._cueFile = 
        `REM Generated by Icecast Metadata Reader NodeJS
REM Recording started at ${this._startDate.toISOString()}
DATE ${this._startDate.toISOString()}
TITLE "${name}"
FILE "${file}" WAVE`;
        this._trackNumber = 1;
    }

    _getFrame(millis) {
        return Math.floor(75 * (millis * 1000 % 1000) / 1000) 
    }

    _getMinutesSeconds(time) {
        const second = Math.floor(time) % 60;
        const minute = Math.floor(time / 60);
        const frame = this._getFrame(time);

        return [minute, second, frame].map(value => value.toString().padStart(2, 0)).join(':');
    }

    addEntry(time, title) {
        const newTrack = `
        TRACK ${this._trackNumber++} AUDIO
          TITLE "${title}"
          INDEX 01 ${this._getMinutesSeconds(time)}`;
        console.log(newTrack);
        this._cueFile += newTrack;
    }
    getCueFile() {
        return this._cueFile;
    }
}

module.exports = CueFileGenerator;