REM COMMENT "Generated by IcecastMetadataRecorder https://github.com/eshaz/icecast-metadata-js"
REM BR "128"
REM GENRE "Covers Eclectic"
REM METAINT "16000"
REM NOTICE1 "<BR>This stream requires <a href="http://www.winamp.com/">Winamp</a><BR>"
REM NOTICE2 "SHOUTcast Distributed Network Audio Server/Linux v1.9.5<BR>"
REM PUB "0"
REM URL "http://somafm.com"
REM DATE "2020-08-07T13:11:17.464Z"
TITLE "Covers: Just covers. Songs you know by artists you don't. [SomaFM]"
FILE "test.ebml" WAVE
  TRACK 1 AUDIO
    REM STREAMURL "http://somafm.com/logos/512/covers512.png"
    TITLE "Berklee String Metal Ensemble - Today"
    INDEX 01 00:00:00
  TRACK 2 AUDIO
    REM STREAMURL "http://somafm.com/logos/512/covers512.png"
    TITLE "Soul Rebels Brass Band - Sweet Dreams Are Made Of This"
    INDEX 01 01:17:00